### PR TITLE
To add support for bcasting one of the arguments

### PR DESCRIPTION
**Pull request by sanchit-misra**
I use least significant 12 bits to specify the broadcasting factor. Bit 13 and 14 are set to 1 if vecidx and vecin, respectively, are broadcasted. We have the following use cases:
1. No one is broadcasted
2. Both are broadcasted using the same broadcasting factor
3. One of them is broadcasted using the broadcasting factor

### CODE REVIEW

**Comment by alheinecke** [comment]
What is broadcasting factor? What is this OP doing?

**Review by alheinecke — CHANGES_REQUESTED** [review]
Can you please add additional script to test these new features?

**Comment by sanchit-misra** [comment]
Sure, let me add it soon.

**Comment by alheinecke** [comment]
any update on this?

**Comment by sanchit-misra** [comment]
I have modified the CPP test file (eltwise_opreduce_idxvecs.c) to enable it to test for the various scenarios this entails. I don't know how to add specific tests. I use the following shell script. It tests for all possible paths:
$ cat test.eltwise_opreduce_idxvecs.sh
for redop in 1 2 3
  do
    for op in 0 1 2 3 4
      do
        for op_order in 0 1
          do
            if [ $op != 0 ]
              then
                if [ $redop = 1 ]
                  then
                    argop_mode=0
                  else
                    argop_mode=3
                fi
              elif [ $redop = 1 ]
                then
                  argop_mode=0
              elif [ $op_order = 0 ]
                then
                  argop_mode=2
              else
                argop_mode=1
            fi
            echo $argop_mode
            #no bcast
            ./eltwise_opreduce_idxvecs 64 64 32 64 64 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            #bcast_lhs
            ./eltwise_opreduce_idxvecs 64 64 32 4 64 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 68 64 32 4 68 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 130 64 32 2 130 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 128 64 32 1 128 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 129 64 32 1 129 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            #bcast_rhs
            ./eltwise_opreduce_idxvecs 64 64 32 64 4 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 68 64 32 68 4 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 130 64 32 130 2 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 128 64 32 128 1 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 129 64 32 129 1 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            #bcast_both
            ./eltwise_opreduce_idxvecs 64 64 32 4 4 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 68 64 32 4 4 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 130 64 32 2 2 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 128 64 32 1 1 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
            ./eltwise_opreduce_idxvecs 129 64 32 1 1 $op $op_order 0 $redop 0 0 $argop_mode 0 10000 0
        done
    done
done

**Comment by hfp** [comment]
You can post code in verbose font/format by using backticks (\`). Embracing a word with single backticks will enable `verbose` words inlined to the sentence. You can also form a block with triple backticks at the begin/end around the block. Like the following:

```text
verbose text
embraced by
triple backticks
```

For blocks, you can also denote the language (common choices are `c`, `bash`, and `fortran`):

\`\`\`c
void my_c_function(int a);  
\`\`\`

which then looks like:

```c
void my_c_function(int a);
```

**Comment by alheinecke** [comment]
Three things we need to close before merge
a) can you please merge with upstream such that the conflicts go away
b) @egeor : I thought our unit tests are auto-generated, so I was expecting some changes to this infrastructure and not and not a single sh file
c) @sanchit-misra : even if the sh file is sufficient just posting it in the issue won't enable the tests. It needs to be part of the unit test scripts of op-reduce.

**Comment by sanchit-misra** [comment]
I have merged my changes with the main branch

**Comment by sanchit-misra** [comment]
Three things we need to close before merge
a) can you please merge with upstream such that the conflicts go away
sanchit-misra: Done
b) @egeor : I thought our unit tests are auto-generated, so I was expecting some changes to this infrastructure and not and not a single sh file
c) @sanchit-misra : even if the sh file is sufficient just posting it in the issue won't enable the tests. It needs to be part of the unit test scripts of op-reduce.
sanchit-misra: Of course, I understand that posting the sh file here won't enable the tests. I need your guidance on how to integrate that sh file into the unit tests scripts of op-reduce.

**Comment by egeor** [comment]
This is the file that generates the opreduce tests:

https://github.com/libxsmm/libxsmm/blob/main/samples/eltwise/kernel_test/create_new_opreduce_simple_test.sh

**Comment by sanchit-misra** [comment]
Perhaps, I am missing something. But, this shell script doesn't seem to have options for providing the vector sizes. I want to provide different sizes to be able to test every path of the code. Does that go in this script or elsewhere?

**Comment by egeor** [comment]
You'd have to enhance the scripts... All I was trying to say is that the various opreduce tests were generated by another script and this shall be the method for generating further tests...

**Comment by alheinecke** [comment]
Do we have a timeline for this? Also automatic code scanning seems to have found issues.

**Comment by sanchit-misra** [comment]
I will try my best to edit the tests this week. Will look at the issues found by automatic tests as well.

**Comment by alheinecke** [comment]
any update on this?

**Comment by alheinecke** [comment]
any update on this?

**Comment by sanchit-misra** [comment]
Still trying to find time for this. Will be OOO next two weeks. So, my estimate is first week of January.

**Comment by hfp** [comment]
Ping...

**Comment by alheinecke** [comment]
any update on this?

**Comment by alheinecke** [comment]
any update on this?

**Comment by hfp** [comment]
I merged this work into `main` (rather than `main_stable`). Backporting it to `main_stable` (if still needed when this is ready) is a minor issue. The merged code along with necessary cleanup can be found in the [feature_broadcast_idx](https://github.com/libxsmm/libxsmm/tree/feature_broadcast_idx) branch. I may soon open a PR for it, but people need to work a bit more on top (please take the branch over).

Status:

* Adjusted sample driver (`eltwise_opreduce_idxvecs.c`) to allow regular leading dimensions. Though, this PR changed the driver to to only allowed broadcasting, i.e., `ld0` and/or `ld1` smaller than `m` with the latter a multiple of leading dimension. However, `eltwise_opreduce_idxvecs` needs to work as before like LD's larger than M.
* Adjusted tests to account for the additional command line argument.
* No actual tests are setup just yet for broadcasting.

Major flaw seems in `generator_mateltwise_reduce_avx_avx512.c`:

* It potentially enabled the broadcast feature according to this PR
* However, some existing `eltwise_unary_reduce` tests broke
* Can stem from fiddling more state into bcast flags  
  (and still using the original definition in some parts)

The latter (`eltwise_unary_reduce`) also uses some broadcasting implemented in `generator_mateltwise_reduce_avx_avx512.c` but some tests are now broken, e.g., `unary_reduce_max_cols_idx_i32_argop1_x_overwrite_bf16_eqld`, `unary_reduce_max_cols_idx_i32_argop1_x_overwrite_bf16_gtld`, `unary_reduce_max_cols_idx_i64_argop1_x_overwrite_bf16_eqld`, and `unary_reduce_max_cols_idx_i64_argop1_x_overwrite_bf16_gtld` (see https://buildkite.com/intel/libxsmm-eltwise/builds/5790).

I have not checked if above broken tests simply miss accuracy/error bounds. I will report this asap.

**Comment by hfp** [comment]
Superseded by #778

**Pull request closed without merging**
