### PR TITLE
16-bit transforms norm_to_vnni4 and vnni4_to_vnni4T for avx512 and avx512_vl256

### PR DESCRIPTION
**Pull request by egeor**
This PR introduces the 16-bit transforms norm_to_vnni4 and vnni4_to_vnni4T for avx512 and avx512_vl256

### CODE REVIEW

**Review by alheinecke — APPROVED** [review]
le

**Comment by egeor** [comment]
The CI went through for the scalar codes on AVX/SSE so we should be good to merge

**Review by alheinecke — COMMENTED** [review]
Do you still want put the norm_to_vnni4t TPP and then calling 64bit normal transpose inside before merging?

**Comment by alheinecke** [comment]
@hfp: please advise when main is functional again, so that we can merge

**Comment by egeor** [comment]
> Do you still want put the norm_to_vnni4t TPP and then calling 64bit normal transpose inside before merging?

OK will add it

**Comment by egeor** [comment]
Now the norm_to_vnni4T 16bit transpose is also in and we can merge back

**Review by alheinecke — APPROVED** [review]

**Pull request merged**
