### PR TITLE
Aarch64 MMLA matrix kernels

### PR DESCRIPTION
**Pull request by breuera**
This is an initial draft to start the development of matrix kernels using matrix multiply-accumulate instructions of ASIMD and SVE (*MMLA):
* [ASIMD BFMMLA](https://developer.arm.com/documentation/ddi0602/2022-06/SIMD-FP-Instructions/BFMMLA--BFloat16-floating-point-matrix-multiply-accumulate-into-2x2-matrix-?lang=en), [ASIMD SMMLA](https://developer.arm.com/documentation/ddi0602/2022-06/SIMD-FP-Instructions/SMMLA--vector---Signed-8-bit-integer-matrix-multiply-accumulate--vector--?lang=en), [ASIMD UMMLA](https://developer.arm.com/documentation/ddi0602/2022-06/SIMD-FP-Instructions/UMMLA--vector---Unsigned-8-bit-integer-matrix-multiply-accumulate--vector--?lang=en), [ASIMD USMMLA](https://developer.arm.com/documentation/ddi0602/2022-06/SIMD-FP-Instructions/USMMLA--vector---Unsigned-and-signed-8-bit-integer-matrix-multiply-accumulate--vector--?lang=en)
* [SVE BFMMLA](https://developer.arm.com/documentation/ddi0602/2022-06/SVE-Instructions/BFMMLA--BFloat16-floating-point-matrix-multiply-accumulate-?lang=en), [SVE FMMLA](https://developer.arm.com/documentation/ddi0602/2022-06/SVE-Instructions/FMMLA--Floating-point-matrix-multiply-accumulate-?lang=en) (no hardware available), [SVE SMMLA](https://developer.arm.com/documentation/ddi0602/2022-06/SVE-Instructions/SMMLA--Signed-integer-matrix-multiply-accumulate-?lang=en), [SVE UMMLA](https://developer.arm.com/documentation/ddi0602/2022-06/SVE-Instructions/UMMLA--Unsigned-integer-matrix-multiply-accumulate-?lang=en), [SVE USMMLA](https://developer.arm.com/documentation/ddi0602/2022-06/SVE-Instructions/USMMLA--Unsigned-by-signed-integer-matrix-multiply-accumulate-?lang=en)

First version:
  * Fixed M=16, N=6, K=8 blocking for BF16 kernels; multiples of the block sizes are supported.
  * Fixed M=16, N=6, K=16 blocking for I8 kernels; multiples of the block sizes are supported.
  * A assumed to be in MMLA format, i.e., (2x4) row-major submatrices with column-major blocking for BF16 and (2x8) row-major submatrices with column-major blocking for I8.
  * B is column-major.
  * C is column-major.
  * ASIMD support only, no SVE supoort.
  * xgemm support for: BF16F32_FLAT, USI8I32, SUI8I32, SSI8I32.
  * Code contains quite some TODOs and dirty shortcuts which have to be worked on.

Graviton3 performance (c7g.large):
```
[fedora@ip-172-31-6-113 xgemm]$ LIBXSMM_VERBOSE=-1 LIBXSMM_TARGET=aarch64 ./kernel 32 24 128 32 128 32 1 1 0 0 0 0 nopf BF16F32_FLAT nobr 1 0 1000000
------------------------------------------------
RUNNING (32x128) X (128x24) = (32x24), BF16F32_FLAT, BR=1
------------------------------------------------
LIBXSMM WARNING: timer is maybe not cycle-accurate!
LIBXSMM-JIT-DUMP(ptr:file) 0xffffb6ccf000 : libxsmm_abi1_aarch64_bf16f32_nn_32x24x128_32_128_32_a1_b1_p0_br0_uh0_si0_tc-abid_avnni0_bvnni0_cvnni0.mxm
function pointer address: ffffb6ccf000
0.000162s for creating jit

Printing Norms:
L1 reference  : 601.097537994384765625
L1 test       : 601.097537994384765625
L2 abs.error  : 0.000000000000000000000000
L2 rel.error  : 0.000000000000000000000000
Linf abs.error: 0.000000000000000000000000
Linf rel.error: 0.000000000000000000000000
Check-norm    : 0.000000000000000000000000

1.175869s for libxsmm
167.202321 GFLOPS for libxsmm
max. error: 0.000000
------------------------------------------------


 Total Max Error 0.000000


LIBXSMM_VERSION: mmla-1.16.3-2707 (25217683)
AARCH64/SP    TRY    JIT    STA    COL
   0..13      0      0      0      0 
  14..23      0      0      0      0 
  24..64      1      1      0      0 
Registry and code: 13 MB + 8 KB (gemm=1)
Uptime: 1.177165 s
```

```
[fedora@ip-172-31-6-113 xgemm]$ LIBXSMM_VERBOSE=-1 LIBXSMM_TARGET=aarch64 ./kernel 32 24 128 32 128 32 1 1 0 0 0 0 nopf SSI8I32 nobr 1 0 1000000
------------------------------------------------
RUNNING (32x128) X (128x24) = (32x24), SSI8I32, BR=1
------------------------------------------------
LIBXSMM WARNING: timer is maybe not cycle-accurate!
LIBXSMM-JIT-DUMP(ptr:file) 0xffff95c50000 : libxsmm_abi1_aarch64_i8i32_nn_32x24x128_32_128_32_a1_b1_p0_br0_uh0_si0_tc-abid_avnni0_bvnni0_cvnni0.mxm
function pointer address: ffff95c50000
0.000297s for creating jit

Printing Norms:
L1 reference  : 3485232
L1 test       : 3485232
L2 abs.error  : 0.000000000000000000000000
L2 rel.error  : 0.000000000000000000000000
Linf abs.error: 0.000000000000000000000000
Linf rel.error: 0.000000000000000000000000
Check-norm    : 0.000000000000000000000000

0.612882s for libxsmm
320.792374 GFLOPS for libxsmm
max. error: 0.000000
------------------------------------------------


 Total Max Error 0.000000


LIBXSMM_VERSION: mmla-1.16.3-2707 (25217683)
AARCH64/SP    TRY    JIT    STA    COL
   0..13      0      0      0      0 
  14..23      0      0      0      0 
  24..64      1      1      0      0 
Registry and code: 13 MB + 8 KB (gemm=1)
Uptime: 0.614356 s
```

llvm-mc paramters for your convenience:
```
[alex@jenalex ~]$ echo "fmmla z0.s, z0.s, z0.s" | llvm-mc -triple=aarch64 --show-encoding -mattr=+i8mm -mattr=+sve -mattr=+f32mm
	.text
	fmmla	z0.s, z0.s, z0.s                // encoding: [0x00,0xe4,0xa0,0x64]
```

```
[alex@jenalex ~]$ echo "0x0 0xe4 0xa0 0x64" | llvm-mc -triple=aarch64 --show-encoding -disassemble -mattr=+i8mm -mattr=+sve  -mattr=+f32mm
	.text
	fmmla	z0.s, z0.s, z0.s                // encoding: [0x00,0xe4,0xa0,0x64]
```

### CODE REVIEW

**Comment by breuera** [comment]
Commit 76df67a adds a SVE version:
* M=32, N=6, K=8 blocking for BF16 input.
* M=32, N=6, K=16 blocking for I8 input.
* xgemm support for: BF16F32_FLAT

Graviton3 performance (c7g.large)
```
[fedora@ip-172-31-6-113 xgemm]$ LIBXSMM_VERBOSE=-1 LIBXSMM_TARGET=neov1 ./kernel 32 24 128 32 128 32 1 1 0 0 0 0 nopf BF16F32_FLAT nobr 1 0 1000000
------------------------------------------------
RUNNING (32x128) X (128x24) = (32x24), BF16F32_FLAT, BR=1
------------------------------------------------
LIBXSMM WARNING: "neov1" code will fail to run on "aarch64"!
LIBXSMM WARNING: timer is maybe not cycle-accurate!
LIBXSMM-JIT-DUMP(ptr:file) 0xffffa9612000 : libxsmm_abi1_neov1_bf16f32_nn_32x24x128_32_128_32_a1_b1_p0_br0_uh0_si0_tc-abid_avnni0_bvnni0_cvnni0.mxm
function pointer address: ffffa9612000
0.000313s for creating jit

Printing Norms:
L1 reference  : 601.097537994384765625
L1 test       : 601.097537994384765625
L2 abs.error  : 0.000000000000000000000000
L2 rel.error  : 0.000000000000000000000000
Linf abs.error: 0.000000000000000000000000
Linf rel.error: 0.000000000000000000000000
Check-norm    : 0.000000000000000000000000

1.100349s for libxsmm
178.677813 GFLOPS for libxsmm
max. error: 0.000000
------------------------------------------------


 Total Max Error 0.000000


LIBXSMM_VERSION: mmla-1.16.3-2707 (25217683)
NEOV1/SP    TRY    JIT    STA    COL
   0..13      0      0      0      0 
  14..23      0      0      0      0 
  24..64      1      1      0      0 
Registry and code: 13 MB + 8 KB (gemm=1)
Uptime: 1.101835 s
```

**Comment by breuera** [comment]
21a4c85 also supports SUI8I32 and SSI8I32 but not USI8I32.
Graviton3 performance (c7g.large):
```
[fedora@ip-172-31-6-113 xgemm]$ LIBXSMM_VERBOSE=-1 LIBXSMM_TARGET=neov1 ./kernel 32 24 128 32 128 32 1 1 0 0 0 0 nopf SSI8I32 nobr 1 0 1000000
------------------------------------------------
RUNNING (32x128) X (128x24) = (32x24), SSI8I32, BR=1
------------------------------------------------
LIBXSMM WARNING: "neov1" code will fail to run on "aarch64"!
LIBXSMM WARNING: timer is maybe not cycle-accurate!
LIBXSMM-JIT-DUMP(ptr:file) 0xffffb81a0000 : libxsmm_abi1_neov1_i8i32_nn_32x24x128_32_128_32_a1_b1_p0_br0_uh0_si0_tc-abid_avnni0_bvnni0_cvnni0.mxm
function pointer address: ffffb81a0000
0.000250s for creating jit

Printing Norms:
L1 reference  : 3485232
L1 test       : 3485232
L2 abs.error  : 0.000000000000000000000000
L2 rel.error  : 0.000000000000000000000000
Linf abs.error: 0.000000000000000000000000
Linf rel.error: 0.000000000000000000000000
Check-norm    : 0.000000000000000000000000

0.580149s for libxsmm
338.892088 GFLOPS for libxsmm
max. error: 0.000000
------------------------------------------------


 Total Max Error 0.000000


LIBXSMM_VERSION: mmla-1.16.3-2708 (25217684)
NEOV1/SP    TRY    JIT    STA    COL
   0..13      0      0      0      0 
  14..23      0      0      0      0 
  24..64      1      1      0      0 
Registry and code: 13 MB + 8 KB (gemm=1)
Uptime: 0.581535 s
```

**Comment by alheinecke** [comment]
The code looks good to me and I'm merging this into the bfmmla branch as we can add then add flags for the new format there etc.
Do want to push some more changes before we do this?

**Comment by breuera** [comment]
Won't touch the code in the next few weeks: please go ahead.
In the long term, one might consider putting the kernel generation into a different wrapper, i.e., not force it into the standard ASIMD/SVE code.

**Pull request merged**
