### PR TITLE
Adding F16 GEMM variants

### PR DESCRIPTION
**Pull request by alheinecke**

### CODE REVIEW

**Review by alheinecke — COMMENTED** [review]
Approved

**Comment by CaoE** [comment]
Hi @alheinecke May I know when libxsmm will support such case :  `
io_generated_code->arch >= LIBXSMM_X86_AVX512_SPR ) &&
              (LIBXSMM_GEMM_GETENUM_AB_COMMON_PREC( l_xgemm_desc_mod.datatype ) == LIBXSMM_DATATYPE_F16) &&
              (LIBXSMM_GEMM_GETENUM_C_PREC( l_xgemm_desc_mod.datatype ) == LIBXSMM_DATATYPE_F16 || LIBXSMM_GEMM_GETENUM_C_PREC( l_xgemm_desc_mod.datatype ) == LIBXSMM_DATATYPE_F32)` ?

**Comment by alheinecke** [comment]
Not sure what you mean, there is GNR and SPR support for F16 GEMM. Can you please be add more details to your question? @egeor  just in case.

**Comment by CaoE** [comment]
@alheinecke I mean it seems F16 GEMM in VNNI layout hasn't been supported yet. https://github.com/libxsmm/libxsmm/pull/769/files#diff-13c297ba78236d6ab7f88f9fd9f883c9bd27fcaf4fa2b8fb79ea836e617cf183R293 Will it be supported in the future ？

**Comment by egeor** [comment]
This is supported for GNR already in the codebase. For SPR we do not support it and it is not in the plans to do so... Since this would not be performance on SPR anyway, most likely the best option is to have the application deal with the reformats/relayouts upfront and call existing high-performance gemm kernels.

**Comment by CaoE** [comment]
@egeor Sorry for not describing it clearly. It seems that there is no support for such gemm with VNNI layout on GNR:  takes fp16 inputs and generates fp32/fp16 output ? https://github.com/libxsmm/libxsmm/blob/main/src/generator_gemm.c#L361

**Comment by egeor** [comment]
I still don't understand...  see here:
https://github.com/libxsmm/libxsmm/blob/main/src/generator_gemm.c#L324 
and here
https://github.com/libxsmm/libxsmm/blob/main/src/generator_gemm.c#L637

**Comment by CaoE** [comment]
@egeor  Oh, I understand. I missed `io_generated_code->arch >= LIBXSMM_X86_AVX512_GNR`. Thank you very much for your patient answer.

**Pull request merged**
