### PR TITLE
Updated and fixed VS projects.

### PR DESCRIPTION
**Pull request by hfp**

### CODE REVIEW

**Comment by hfp** [comment]
A real review may be skipped. Though, this is not actually tested by CI. Further, this change assumes some changes not yet sent as PR.

**Comment by alheinecke** [comment]
if  we need more changes please incl. in the PR.

**Comment by hfp** [comment]
> if we need more changes please incl. in the PR.

It can be merged now "breaks nothing" (or kept until other/entangled changes are PRd).

**Comment by alheinecke** [comment]
closed as it is supersede by #928 which incl. fixes for all additions since May.

**Pull request closed without merging**
