### PR TITLE
Eltwise reduce: bcasting one of the arguments

### PR DESCRIPTION
**Pull request by hfp**
See #696, and https://github.com/libxsmm/libxsmm/pull/696#issuecomment-1583266073 in particular.

### CODE REVIEW

**Comment by hfp** [comment]
Here is a list of examples on CLX (and perhaps everywhere else), which miss validation likely due to incorrect results:

```bash
./eltwise_unary_reduce 42 84 42 1 0 0 1 BF16 42 1 1 0
./eltwise_unary_reduce 60 102 100 1 0 0 1 BF16 42 1 1 0
./eltwise_unary_reduce 26 59 26 1 0 0 1 BF16 42 0 1 0
./eltwise_unary_reduce 54 137 100 1 0 0 1 BF16 42 0 1 0
```

**Comment by sanchit-misra** [comment]
> ```shell
> ./eltwise_unary_reduce 54 137 100 1 0 0 1 BF16 42 0 1 0
> ```

This error was due to a change in policy of picking argop in case of equal values. The previous policy would pick a later entry while the new policy I introduced (to be compatible with DGL) picks the earlier entry. My latest commit # b7fa0f2 fixes this by changing the reference result according to the new policy.

**Comment by sanchit-misra** [comment]
Hi Hans, just following up to see if you got to try out the fixed code?

**Comment by hfp** [comment]
@alheinecke Let's sync with Alex once more. There was some pending work in competition to this PR.

In any case, we can keep this PR alive (merge `main` branch from time to time). At the moment, something on Graviton3 seems to fail, which is specific to this PR. If it helps, I can share failing cases and how you can access GVT3.

**Comment by anko-intel** [comment]
Hi,
Is there any work ongoing in this PR? 
I have used [feature_broadcast_idx](https://github.com/libxsmm/libxsmm/tree/feature_broadcast_idx) branch with [DGL](https://github.com/dmlc/dgl) and observed 12% improvements on GAT due to using LIBXSMM SpMM implementation for cases with broadcasting. It would be great to use this PR code from the main(_stable) branch.

**Comment by hfp** [comment]
> Hi, Is there any work ongoing in this PR? I have used [feature_broadcast_idx](https://github.com/libxsmm/libxsmm/tree/feature_broadcast_idx) branch with [DGL](https://github.com/dmlc/dgl) and observed 12% improvements on [GAT ](https://github.com/dmlc/dgl/blob/master/examples/pytorch/ogb/ogbn-products/gat/gat.py) due to using LIBXSMM SpMM implementation for cases with broadcasting. It would be great to use this PR code from the main(_stable) branch.

This PR is on hold and to be replaced by other work. Thank you for your feedback. @alheinecke FYI

**Comment by alheinecke** [comment]
@anko-intel This feature will to 99% not land.

@ska278 works on a new implementation using basic TPPs (more readable code) it's already landed in LIBXSMM. @ska278  is right now testing performance in DGL-like kernels.

**Comment by alheinecke** [comment]
as we will remove opreduce from, I'm closing this PR

**Pull request closed without merging**
